DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS BOOK (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  author VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  ISBN VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS PEOPLE;

CREATE TABLE IF NOT EXISTS PEOPLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS PEOPLE_BOOK;

CREATE TABLE IF NOT EXISTS PEOPLE_BOOK (
  people_id INT NOT NULL,
  books_id INT NOT NULL,
  FOREIGN KEY (people_id) REFERENCES PEOPLE(id),
  FOREIGN KEY (books_id) REFERENCES BOOK(id)
);
